version: "3.0"
services:
  opcua-reader:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      MODULE_NAME: "OPC UA Reader"
      MODULE_TYPE: "Input"
      EGRESS_URLS: "https://testdockercompose.free.beeceptor.com"
      INGRESS_HOST: "0.0.0.0"
      INGRESS_PORT: "80"
      MAX_RETRY: '1'
      NODE_ID: '3'
      VARIABLE_LIST: 'Scalar_Simulation_Float'
      OPC_UA_SERVER: 'opc.tcp://localhost:26543'
      OPC_UA_USERNAME: ''
      OPC_UA_PASSWORD: ''

    ports:
      - 80:80